### ISSUE TITLE
libGL error: MESA-LOADER

### ISSUE THREAD

**Issue by SarahAlidoost** [EcoExtreML/processing#6]
On some linux systems, the notebook [notebooks/run_model_in_notebook.ipynb](https://github.com/EcoExtreML/processing/pull/5/files#diff-1751787c308b01a0e2f736c276a5c0797213e6f7e5f4c60a8733f1f03c2dcfdb) might result an error as:

```python
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```

For more info, see this [message](https://github.com/EcoExtreML/processing/pull/5#issuecomment-1126174618). However, the notebook run can be successful.

**Comment by sverhoeven** [comment]
Can you show your conda list? I expect some conda packages are installed that require a gpu to be installed. You might be able to install the cpu version of those packages.

**Comment by SarahAlidoost** [comment]
> Can you show your conda list? I expect some conda packages are installed that require a gpu to be installed. You might be able to install the cpu version of those packages.

thanks. This is the[ environment file](https://github.com/EcoExtreML/processing/blob/main/environment.yml). @geek-yang  found that if we append the `opengl` path of matlab to `LD_LIBRARY_PATH` variable, the issue is fixed.
